### ISSUE TITLE
SIG.com Logo

### ISSUE THREAD

**Issue by kevinschoonover** [sigdotcom/acm.mst.edu#20]
# Description

SIG.com needs some logo designs, preferably like:
1) A banner
2) An Icon (128x128 and higher)

**Comment by dylanelznic** [comment]
![dotcomlogo_0 2](https://cloud.githubusercontent.com/assets/13475065/22769718/2060b304-ee50-11e6-8526-58d716ebcb1e.png)

Just threw together an idea I had

**Comment by user404d** [comment]
I really like it -- a lot -- and it also looks really familiar. What was this inspired by?

**Comment by dylanelznic** [comment]
Thank you! It's just an idea, so if this isn't anything like what was expected then we can just scrap it. It was just one of the scribbles that I came up with, not directly inspired by anything in particular.  I actually looked though a lot of existing logos to make sure that it didn't look like something that was already out there. The only theme I could find was the use of '</>' generally being associated with HTML.

**Comment by dylanelznic** [comment]
![sigcombubble](https://cloud.githubusercontent.com/assets/13475065/23965611/87ce7692-0986-11e7-94cc-3fe64e705477.png)

**Comment by dylanelznic** [comment]
I can't tell if the inside isn't centered or if me eyes are bad

**Comment by kevinschoonover** [comment]
It looks a tad skewed to the right, but that may be just due to the chat bubble tail.

**Comment by dylanelznic** [comment]
![sigcombubbleicon](https://cloud.githubusercontent.com/assets/13475065/24085179/11f4a940-0cc5-11e7-8191-3b26e46e0e51.png)

**Comment by kevinschoonover** [comment]
I think we've found a good logo.
