### ISSUE TITLE
Fix Timezones

### ISSUE THREAD

**Issue by zdw27f** [sigdotcom/acm.mst.edu#44]
- Fix timezones so that whenever Django prints them out, the correct time is printed out according to the specified user's timezone.
- Possibly look into using [pytz with Django](https://docs.djangoproject.com/en/1.10/topics/i18n/timezones/). (Needs to be tested while not on a localhost to see if it works!)

**Comment by zdw27f** [comment]
I solved this issue in the current branch I'm working on with creating events and dynamically changing the homepage (as far as events go). Solved this problem using [django-tz-detect](https://pypi.python.org/pypi/django-tz-detect). I'll add this fix when I finish everything with the branch I'm on.

**Comment by zdw27f** [comment]
Also, just important notes about using this app to fix the problem (it mentions it on the page I linked):

- Django’s timezone awareness will not be available on the first page view
- This method requires JavaScript
- Timezone detection is done entirely from the user’s GMT offset, not from their location

If anyone is opposed to using this app to fix the problem, let me know and I'll remove it from my current branch until we find a better solution.

**Comment by kevinschoonover** [comment]
Preferably, we should detect and change the timezone from entirely the back end. I will try to investigate ways of doing things.

**Comment by kevinschoonover** [comment]
For right now, the solution for events will be to add (Central) or append something with that connotation to event times. The `official` solution is to use a timezone settings and use that with middleware. Will revisit later. Closing for now.
