### ISSUE TITLE
Event Creation/Login

### ISSUE THREAD

**Issue by kevinschoonover** [sigdotcom/acm.mst.edu#7]
# Event Creation
## Purpose
In order to automate the event creation process for each of the SIGs, allowing for some unique automation purposes, we need to make a event creation system.
## Tasks
1) Develop a Event Creation form which allows the SIGs to input any necessary data in order to create an Event
    + Ability to add a flier/poster which is automatically added to the website?
2) Develop an Event list view which displays all of the current/future events which are going on in ACM. Moreover, this should have some sort of 'archived' section which displays all previous events.
### Long Term
1) Automatically create the event on the ACM calendar.
2) Automatically send out reminder emails to any person registered for the event on a scheduled time interval

# Event Login
## Purpose
In order for ACM to be able to properly track member participation as well as gauge interests in different topics, we need some login system which allows us to more properly match users with what they want.
## Tasks
1) Create a login system which enforces a user to be on-site/actually participating at the event in order to count
    + Ideas:
      + QR Codes
      + Secret Keys written on the board

**Comment by zdw27f** [comment]
Can't figure out how to assign this to myself so I guess I'll just comment on it. I'm going to attempt to work on it, no guarantees of figuring it out though...

**Comment by user404d** [comment]
You're good to go now.

**Comment by zdw27f** [comment]
Where exactly should I be working on creating the event creation in the django folders? At first, I was thinking it was under the Events folder since its the events app, but now I'm thinking it should be under the User folder since only Users with certain rights should be able to create the events I'm guessing.

**Comment by kevinschoonover** [comment]
Feature Request: Ability to Edit events that have already been submitted via a nice GUI which displays all current events.

**Comment by kevinschoonover** [comment]
Closed in #82
